export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const SEARCH_SHOU_REQUEST = 'SEARCH_SHOU_REQUEST';
export const SEARCH_SHOU_SUCCESS = 'SEARCH_SHOU_SUCCESS';
export const SEARCH_SHOU_FAIL = 'SEARCH_SHOU_FAIL';

export const SEARCH_NUM_REQUEST = 'SEARCH_NUM_REQUEST';
export const SEARCH_NUM_SUCCESS = 'SEARCH_NUM_SUCCESS';
export const SEARCH_NUM_FAIL = 'SEARCH_NUM_FAIL';